name = "ARCEMEAnalysis"
uuid = "563f603e-cf7b-4a8e-a33e-18ac0a6a317f"
version = "0.1.0-DEV"
authors = ["Melanie Weynants <mweynants@bgc-jena.mpg.de>", "Fabian Gans <fgans@bgc-jena.mpg.de>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Minio = "4281f0d9-7ae0-406e-9172-b7277c1efa20"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"

[compat]
CSV = "0.10.15"
Colors = "0.13.1"
DataStructures = "0.18.22"
Dates = "1.11.0"
DimensionalData = "0.29.24"
Minio = "0.2.2"
ProgressMeter = "1.11.0"
Proj = "1.9.0"
Statistics = "1.11.1"
YAXArrays = "0.7.0"
Zarr = "0.9.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
