name = "ARCEMEAnalysis"
uuid = "563f603e-cf7b-4a8e-a33e-18ac0a6a317f"
authors = ["Melanie Weynants <mweynants@bgc-jena.mpg.de>", "Fabian Gans <fgans@bgc-jena.mpg.de>"]
version = "0.1.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
